### ISSUE TITLE
Ansible FQCN: Hashivault seems to be deprecated

### ISSUE THREAD

**Issue by ra-rau** [osism/ansible-collection-commons#321]
At this time we use this one:

```yaml
- name: Create secret
  no_log: true
  hashivault_secret:
    authtype: token
    url: "{{ vault_url }}"
    token: "{{ vault_token }}"
    mount_point: kv
    secret: "{{ item.key }}"
    data:
      value: "{{ item.value }}"
  loop: "{{ secrets|dict2items }}"
```

But hashivault seems to be deprecated. Maybe we better use something like this:
https://docs.ansible.com/ansible/2.9/plugins/lookup/hashi_vault.html
or:
https://docs.ansible.com/ansible/latest/collections/community/hashi_vault/hashi_vault_lookup.html#ansible-collections-community-hashi-vault-hashi-vault-lookup

For example:

```yaml
- name: Return all secrets from a path
  ansible.builtin.debug:
    msg: "{{ lookup('hashi_vault', 'secret=secret/hello token=c975b780-d1be-8016-866b-01d0f9b688a5 url=http://myvault:8200')}}"
```
