### ISSUE TITLE
local_action: Seems to be deprecated

### ISSUE THREAD

**Issue by ra-rau** [osism/ansible-collection-commons#322]
In the following yaml there are tasks that are marked as deprecated:
https://github.com/osism/ansible-collection-commons/blob/main/roles/network/tasks/type-netplan.yml

Maybe a solution is:
```yaml
- name: Prepare netplan configuration template
  ansible.builtin.template:
    src: netplan/01-osism.yaml.j2
    dest: "/tmp/{{ inventory_hostname }}-01-osism.yaml.j2"
    mode: 0644
  delegate_to: localhost
```
